# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 18:41
from __future__ import unicode_literals

import aqsa_apps.import_from_file.models
import aqsa_apps.import_from_file.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet_tag_etc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFromFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('file', models.FileField(upload_to=aqsa_apps.import_from_file.models.upload_to, validators=[aqsa_apps.import_from_file.validators.file_size, aqsa_apps.import_from_file.validators.file_extension], verbose_name='File')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('no_error', models.NullBooleanField(verbose_name='No error')),
                ('num_imported_rows', models.PositiveSmallIntegerField(default=0, verbose_name='* Number of imported rows')),
                ('success', models.BooleanField(default=False, verbose_name='Import finished successfully')),
                ('bank', models.CharField(choices=[('rub_sberbank', 'Sberbank (Card in Russian Federation ruble currency)')], max_length=20, null=True, verbose_name='Bank')),
                ('variety', models.PositiveSmallIntegerField(choices=[(1, 'Bank Statement'), (2, 'CSV with Wallets'), (3, 'CSV with Categories'), (4, 'CSV with Tags'), (5, 'CSV with Contacts'), (6, 'CSV with Transactions'), (7, 'Backup (All in one ZIP)')], verbose_name='Variety of uploaded file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_tag_etc.Wallet', verbose_name='Wallet')),
            ],
            options={
                'db_table': 'import_from_file',
                'ordering': ('-date', '-pk'),
            },
        ),
    ]
