# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonToDeleteAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'reason_to_delete',
            },
        ),
    ]
